doctrine:
    dbal:
        default_connection: snut
        connections:
            snut: 
                url: '%env(resolve:DATABASE_URL)%snutplateform'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        #profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: snut_plateform
        entity_managers:
            snut_plateform:
                connection: snut
                dql:
                    string_functions:
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                        JSON_CONTAINS : DoctrineExtensions\Query\Mysql\JsonContains
                    datetime_functions:
                        LAST_DAY: DoctrineExtensions\Query\Mysql\LastDay
                        YEAR : DoctrineExtensions\Query\Mysql\Year
                        MONTH : DoctrineExtensions\Query\Mysql\Month
                        IFNULL : DoctrineExtensions\Query\Mysql\IfNull
                        CONCAT_WS : DoctrineExtensions\Query\Mysql\ConcatWs
                        REGEXP : DoctrineExtensions\Query\Mysql\Regexp
                        DATE : DoctrineExtensions\Query\Mysql\Date
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
        

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
